import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, ClipboardCheck, Users } from "lucide-react";
import { SectionHeading } from "../../components/SectionHeading";

export const metadata: Metadata = { title: "Corporate Training | DMECH Academy", description: "Discuss practical technician development for fleet operators, company workshops, and corporate cohorts with DMECH Academy.", alternates: { canonical: "/corporate-training" } };

const OPTIONS = [[Building2, "Company workshop development", "A structured development path for technicians working inside an organisation’s own maintenance operation."], [Users, "Fleet technician cohorts", "Training designed around the powertrain mix, recurring faults, and practical needs of a fleet team."], [ClipboardCheck, "Apprentice pipeline", "A possible route from intake and foundation through bay placement and Level 1 sign-off." ]] as const;

export default function CorporateTrainingPage() { return <main><section className="academy-page-hero"><div className="academy-container"><div className="academy-kicker">For organisations</div><h1>Develop the people behind your uptime.</h1><p>Discuss practical technician development for fleets, company workshops, and organisations building a stronger technical pipeline.</p><div className="academy-actions"><Link href="/register-interest" className="academy-button academy-button-primary">Submit a training enquiry <ArrowRight size={16} /></Link></div></div></section><section className="academy-section academy-section-white"><div className="academy-container"><SectionHeading eyebrow="Possible starting points" title="Training shaped around the work." text="Corporate programmes are discussed with DMECH first so the syllabus, cohort, delivery setting, and reporting approach fit the organisation." /><div className="academy-method-grid">{OPTIONS.map(([Icon, title, text]) => <article className="academy-method-card" key={title}><Icon size={23} /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="academy-dark-band"><div className="academy-container academy-split"><div><div className="academy-kicker">Start a conversation</div><h2>Tell us what your technicians need to do better.</h2><p>Share your organisation, technician group, powertrain mix, and the capability you want to develop. DMECH will confirm the appropriate next step.</p></div><Link href="/register-interest" className="academy-button academy-button-light">Request a cohort discussion <ArrowRight size={16} /></Link></div></section></main>; }
