import type { Metadata } from "next";
import { BookOpen, CheckCircle2, Repeat2, Search, ShieldCheck, Wrench } from "lucide-react";
import { SectionHeading } from "@academy-components/SectionHeading";

export const metadata: Metadata = { title: "How It's Taught | DMECH Academy", description: "Learn how DMECH Academy connects theory, workshop practice, diagnosis, assessment, and technician progression.", alternates: { canonical: "/how-its-taught" } };

const METHODS = [[Wrench, "Workshop-first learning", "The working workshop is the classroom. Training connects to the conditions, tools, decisions, and discipline of real work."], [BookOpen, "Theory that supports practice", "Concepts are introduced because they help a technician understand a system or make a better next test."], [Search, "Guided diagnostics", "Learners practise moving from a reported symptom to a test that can confirm or eliminate a possibility."], [Repeat2, "Practical repetition", "Good technique becomes reliable through supervised repetition, not a single demonstration."], [ShieldCheck, "Instructor assessment", "Instructors observe the method, the evidence, and the limits of what the learner can claim."], [CheckCircle2, "Competency progression", "Progression follows demonstrated capability and documented sign-off." ]] as const;

export default function HowItsTaughtPage() { return <main><section className="academy-page-hero"><div className="academy-container"><div className="academy-kicker">How it&apos;s taught</div><h1>Learn it. Work it. Prove it.</h1><p>Training is built around a simple idea: theory matters most when it improves the work happening in front of you.</p></div></section><section className="academy-section academy-section-white"><div className="academy-container"><SectionHeading eyebrow="The method" title="A training loop, not a lecture queue." text="Every stage brings the learner closer to making, explaining, and verifying better technical decisions." /><div className="academy-method-grid">{METHODS.map(([Icon, title, text]) => <article className="academy-method-card" key={title}><Icon size={23} /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="academy-section"><div className="academy-container academy-loop"><div className="academy-loop-step"><span>01</span><strong>Learn</strong><small>Understand the system</small></div><div>→</div><div className="academy-loop-step"><span>02</span><strong>Practise</strong><small>Apply the method</small></div><div>→</div><div className="academy-loop-step"><span>03</span><strong>Assess</strong><small>Show the evidence</small></div><div>→</div><div className="academy-loop-step"><span>04</span><strong>Progress</strong><small>Take on responsibility</small></div></div></section></main>; }
